"""
intelligent_refresh.py — Intelligent slide refresh orchestrated by Claude Code.

Pipeline:
  1. embed-config: Write a lightweight config into the PPTX as a Custom XML Part
     (slide IDs, data source assignments, data_sources catalog)
  2. read: Extract visual context from slides for Claude Code interpretation
  3. refresh-deck: Read embedded config + spec.json, fetch data, refresh all slides
  4. headline: Write data-grounded headlines into refreshed slides

The PPTX carries an embedded config (source of truth for structure).
The spec.json carries detailed per-component mappings (generated by Claude Code).
When the deck is edited in PowerPoint (reorder/add/delete), the embedded config
is used to reconcile spec.json automatically.

Usage:
    python -m slidegen.intelligent_refresh embed-config --pptx deck.pptx --config config.yaml
    python -m slidegen.intelligent_refresh read --pptx deck.pptx [--slide 0]
    python -m slidegen.intelligent_refresh refresh-deck --spec deck.json
    python -m slidegen.intelligent_refresh headline --pptx deck.pptx --slide 0 --text "..."
"""
from __future__ import annotations

import json
import os
import shutil
import sys
import uuid
import zipfile
from pathlib import Path

import pandas as pd
import yaml
from dotenv import load_dotenv
from pptx import Presentation
from pptx.chart.data import CategoryChartData, XyChartData
from pptx.enum.chart import XL_CHART_TYPE

REPO_ROOT = Path(__file__).resolve().parents[1]
load_dotenv(REPO_ROOT / ".env", override=True)

# Namespace for our Custom XML Part (distinguishes from Connector's parts)
SLIDEGEN_CONFIG_NS = "http://slidegen.zoomrx.com/config"


# ══════════════════════════════════════════════════════════════════════════════
# Embedded Config — read/write lightweight config inside PPTX
# ══════════════════════════════════════════════════════════════════════════════

def read_embedded_config(pptx_path: str) -> dict | None:
    """Read the SlideGen config embedded in a PPTX as a Custom XML Part.

    Returns the config dict, or None if no SlideGen config is embedded.
    """
    try:
        with zipfile.ZipFile(pptx_path, "r") as z:
            for name in z.namelist():
                if not name.startswith("customXml/item") or not name.endswith(".xml"):
                    continue
                if "Props" in name:
                    continue
                blob = z.read(name).decode("utf-8", errors="replace")
                if SLIDEGEN_CONFIG_NS in blob:
                    # Extract JSON between the XML tags
                    start = blob.index("{")
                    end = blob.rindex("}") + 1
                    return json.loads(blob[start:end])
    except Exception:
        pass
    return None


def write_embedded_config(pptx_path: str, config: dict) -> None:
    """Write (or overwrite) the SlideGen config as a Custom XML Part in the PPTX.

    The config is stored as JSON inside an XML wrapper with our namespace.
    If a SlideGen config already exists, it is replaced. Otherwise, a new
    Custom XML Part is added.
    """
    config_json = json.dumps(config, indent=2, ensure_ascii=False)
    config_xml = (
        f'<SlideGenConfig xmlns="{SLIDEGEN_CONFIG_NS}">'
        f"{config_json}"
        f"</SlideGenConfig>"
    )

    item_id = str(uuid.uuid4()).upper()
    props_xml = (
        f'<?xml version="1.0" encoding="UTF-8" standalone="no"?>'
        f'<ds:datastoreItem ds:itemID="{{{item_id}}}" '
        f'xmlns:ds="http://schemas.openxmlformats.org/officeDocument/2006/customXml">'
        f'<ds:schemaRefs>'
        f'<ds:schemaRef ds:uri="{SLIDEGEN_CONFIG_NS}"/>'
        f'</ds:schemaRefs>'
        f'</ds:datastoreItem>'
    )

    tmp_path = pptx_path + ".tmp"
    existing_item = None

    with zipfile.ZipFile(pptx_path, "r") as zin:
        # Find existing SlideGen config part (if any)
        for name in zin.namelist():
            if name.startswith("customXml/item") and name.endswith(".xml") and "Props" not in name:
                blob = zin.read(name).decode("utf-8", errors="replace")
                if SLIDEGEN_CONFIG_NS in blob:
                    existing_item = name
                    break

        with zipfile.ZipFile(tmp_path, "w", zipfile.ZIP_DEFLATED) as zout:
            for item in zin.infolist():
                if existing_item and item.filename == existing_item:
                    # Replace existing config
                    zout.writestr(item, config_xml.encode("utf-8"))
                elif existing_item and item.filename == existing_item.replace("item", "itemProps"):
                    zout.writestr(item, props_xml.encode("utf-8"))
                else:
                    zout.writestr(item, zin.read(item.filename))

            if not existing_item:
                # Add new part — find next available number
                existing_nums = []
                for n in zin.namelist():
                    if n.startswith("customXml/item") and n.endswith(".xml") and "Props" not in n:
                        try:
                            num = int(n.replace("customXml/item", "").replace(".xml", ""))
                            existing_nums.append(num)
                        except ValueError:
                            pass
                next_num = max(existing_nums, default=0) + 1
                zout.writestr(f"customXml/item{next_num}.xml", config_xml.encode("utf-8"))
                zout.writestr(f"customXml/itemProps{next_num}.xml", props_xml.encode("utf-8"))

    os.replace(tmp_path, pptx_path)


def generate_embedded_config(pptx_path: str) -> dict:
    """Generate a config from the current state of a PPTX.

    Scans all slides: assigns a stable ID to each, detects charts/tables,
    and creates a lightweight manifest. Does NOT determine data_source
    assignments — that's Claude Code's job.
    """
    prs = Presentation(pptx_path)
    slides = []

    for si, slide in enumerate(prs.slides):
        n_charts = sum(1 for s in slide.shapes if s.has_chart)
        n_tables = sum(1 for s in slide.shapes if s.has_table)

        # Extract headline for identification
        headline = ""
        for shape in slide.shapes:
            if shape.has_text_frame:
                top = round((shape.top or 0) / 914400, 2)
                text = shape.text_frame.text.strip()
                if top < 1.5 and len(text) > len(headline):
                    headline = text

        # Collect shape names (stable identifiers for components)
        components = []
        for shape in slide.shapes:
            if shape.has_chart:
                components.append({"type": "chart", "name": shape.name})
            elif shape.has_table:
                components.append({"type": "table", "name": shape.name})

        slides.append({
            "id": f"slide_{si:03d}",
            "index": si,
            "headline": headline[:100],
            "charts": n_charts,
            "tables": n_tables,
            "components": components,
            "data_source": None,  # Claude Code fills this in
        })

    return {
        "version": "1.0",
        "source_deck": Path(pptx_path).name,
        "total_slides": len(prs.slides),
        "slides": slides,
        "data_sources": {},
    }


def reconcile_spec_with_config(spec: dict, config: dict) -> dict:
    """Reconcile a spec.json against the PPTX's embedded config.

    Detects:
    - Reordered slides (slide_id moved to a different index)
    - Added slides (in config but not in spec)
    - Deleted slides (in spec but not in config)

    Returns an updated spec with corrected slide_index values and
    flags for added/deleted slides.
    """
    config_slides = {s["id"]: s for s in config.get("slides", [])}
    spec_slides = {s.get("slide_id", f"slide_{s['slide_index']:03d}"): s
                   for s in spec.get("slides", [])}

    updated_slides = []
    changes = {"reordered": [], "added": [], "deleted": [], "unchanged": []}

    # Match spec slides to config slides by ID
    for cfg_slide in config.get("slides", []):
        sid = cfg_slide["id"]
        new_index = cfg_slide["index"]

        if sid in spec_slides:
            s = spec_slides[sid]
            old_index = s["slide_index"]
            s["slide_index"] = new_index
            if old_index != new_index:
                changes["reordered"].append({"id": sid, "old": old_index, "new": new_index})
            else:
                changes["unchanged"].append(sid)
            updated_slides.append(s)
        else:
            # New slide — add placeholder
            changes["added"].append({"id": sid, "index": new_index,
                                     "headline": cfg_slide.get("headline", "")})
            updated_slides.append({
                "slide_id": sid,
                "slide_index": new_index,
                "data_source": cfg_slide.get("data_source"),
                "components": [],
                "_needs_interpretation": True,
            })

    # Find deleted slides (in spec but not in config)
    config_ids = set(s["id"] for s in config.get("slides", []))
    for sid, s in spec_slides.items():
        if sid not in config_ids:
            changes["deleted"].append({"id": sid, "index": s["slide_index"]})

    spec["slides"] = updated_slides
    # Merge data_sources from config into spec
    for key, val in config.get("data_sources", {}).items():
        if key not in spec.get("data_sources", {}):
            spec.setdefault("data_sources", {})[key] = val

    return {"spec": spec, "changes": changes}

_CHART_TYPE_MAP = {
    XL_CHART_TYPE.BAR_STACKED_100: "bar_stacked_100_horizontal",
    XL_CHART_TYPE.BAR_CLUSTERED: "bar_clustered_horizontal",
    XL_CHART_TYPE.COLUMN_CLUSTERED: "column_clustered_vertical",
    XL_CHART_TYPE.COLUMN_STACKED_100: "column_stacked_100_vertical",
    XL_CHART_TYPE.LINE_MARKERS: "line_markers_trended",
    XL_CHART_TYPE.LINE: "line_markers_trended",
    XL_CHART_TYPE.XY_SCATTER: "xy_scatter_abacus",
    XL_CHART_TYPE.DOUGHNUT: "doughnut_default",
}


def _in(emu):
    """Convert EMU to inches, rounded to 2 decimal places."""
    return round(emu / 914400, 2) if emu else 0.0


# ══════════════════════════════════════════════════════════════════════════════
# Phase 1: Read — extract slide context
# ══════════════════════════════════════════════════════════════════════════════

def read_slide_context(pptx_path: str, slide_index: int = 0) -> dict:
    """Extract all visual context from one slide: shapes, positions, text,
    chart data, table data, group shape labels.

    Returns a dict ready to be printed/read by Claude Code.
    """
    prs = Presentation(pptx_path)
    slide = prs.slides[slide_index]

    shapes = []
    for shape in slide.shapes:
        left, top = _in(shape.left), _in(shape.top)
        width, height = _in(shape.width), _in(shape.height)
        base = {
            "name": shape.name, "left": left, "top": top,
            "width": width, "height": height,
        }

        if shape.has_chart:
            chart = shape.chart
            plot = chart.plots[0]
            cats = [str(c) for c in plot.categories] if plot.categories else []
            s_names = [str(s.name) for s in plot.series]
            s_vals = {}
            for s in plot.series:
                try:
                    s_vals[str(s.name)] = [
                        round(float(v), 4) if v else 0
                        for v in s.values
                    ][:4]
                except Exception:
                    pass
            shapes.append({
                **base, "type": "chart",
                "chart_pattern": _CHART_TYPE_MAP.get(chart.chart_type, "unknown"),
                "series_names": s_names, "categories": cats,
                "series_values": s_vals,
            })

        elif shape.has_table:
            tbl = shape.table
            nr, nc = len(tbl.rows), len(tbl.columns)
            headers = (
                [tbl.cell(0, c).text.strip() for c in range(nc)]
                if nr > 0 else []
            )
            sample = []
            for r in range(1, min(nr, 4)):
                sample.append([tbl.cell(r, c).text.strip() for c in range(nc)])
            shapes.append({
                **base, "type": "table",
                "row_count": nr, "col_count": nc,
                "headers": headers, "sample_rows": sample,
            })

        elif shape.has_text_frame:
            text = shape.text_frame.text.strip()
            if text:
                shapes.append({**base, "type": "text", "text": text[:300]})

        # Group shape children with text
        try:
            if hasattr(shape, 'shapes'):
                for child in shape.shapes:
                    if child.has_text_frame:
                        t = child.text_frame.text.strip()
                        if t:
                            shapes.append({
                                "name": f"{shape.name}/{child.name}",
                                "left": left, "top": top,
                                "width": width, "height": height,
                                "type": "label", "text": t[:200],
                            })
        except Exception:
            pass

    shapes.sort(key=lambda s: (s["left"], s["top"]))

    return {
        "pptx_path": str(pptx_path),
        "slide_index": slide_index,
        "shapes": shapes,
    }


def format_slide_for_interpretation(context: dict) -> str:
    """Format the slide context as a readable text description for Claude Code
    to interpret."""
    lines = []
    lines.append(f"=== Slide {context.get('slide_index', 0)} from {context.get('pptx_path', '?')} ===")
    lines.append("")

    for s in context.get("shapes", []):
        stype = s.get("type", "unknown")
        pos = f"({s['left']:.1f}\", {s['top']:.1f}\") {s['width']:.1f}\"x{s['height']:.1f}\""

        if stype == "chart":
            lines.append(f"[CHART] {s['name']} at {pos}")
            lines.append(f"  Pattern: {s.get('chart_pattern', '?')}")
            lines.append(f"  Categories: {s.get('categories', [])}")
            lines.append(f"  Series: {s.get('series_names', [])}")
            for sn, sv in s.get("series_values", {}).items():
                lines.append(f"    {sn}: {sv}")
            lines.append("")

        elif stype == "table":
            lines.append(f"[TABLE] {s['name']} at {pos}")
            lines.append(f"  {s.get('row_count', '?')} rows x {s.get('col_count', '?')} cols")
            lines.append(f"  Headers: {s.get('headers', [])}")
            for row in s.get("sample_rows", []):
                lines.append(f"    {row}")
            lines.append("")

        elif stype == "text":
            lines.append(f"[TEXT] {s['name']} at {pos}")
            lines.append(f"  \"{s.get('text', '')}\"")
            lines.append("")

        elif stype == "label":
            lines.append(f"[LABEL] {s['name']} at {pos}")
            lines.append(f"  \"{s.get('text', '')}\"")
            lines.append("")

    return "\n".join(lines)


def format_data_for_interpretation(df: pd.DataFrame) -> str:
    """Format fetched data as a readable summary for Claude Code."""
    if df.empty:
        return "No data fetched."

    lines = []
    lines.append(f"=== Fetched Data: {len(df)} records, {len(df.columns)} columns ===")
    lines.append("")
    lines.append(f"Columns: {sorted(df.columns.tolist())}")
    lines.append("")

    for col in df.columns:
        unique = df[col].dropna().unique()
        if len(unique) <= 20:
            lines.append(f"  {col}: {sorted(str(v) for v in unique)}")

    lines.append("")
    lines.append("First 5 rows:")
    lines.append(df.head(5).to_string(index=False))

    return "\n".join(lines)


# ══════════════════════════════════════════════════════════════════════════════
# Data Fetching
# ══════════════════════════════════════════════════════════════════════════════

def fetch_synapse_data(data_lineage: dict) -> tuple[list[dict], pd.DataFrame]:
    """Fetch records from Synapse API using data lineage dict.

    Uses SynapseClient (synapse-cli) so auth is resolved automatically via
    the CLI's fallback chain — works with sk_* keys, cached JWT, Azure AD.
    SYNAPSE_API_URL must be set in .env; no explicit key is required.

    Returns (records_list, dataframe).
    """
    import time
    from synapse_cli import SynapseClient
    from synapse_cli.errors import SynapseError

    base_url = os.environ.get("SYNAPSE_API_URL", "").rstrip("/")
    if not base_url:
        return [], pd.DataFrame()

    client = SynapseClient(base_url=base_url)

    payload = {
        "project_id": data_lineage["project_id"],
        "reporting_plan_id": data_lineage["reporting_plan_id"],
        "analysis_ids": data_lineage["analysis_ids"],
        "segment_ids": data_lineage.get("segment_ids", []),
        "setup_type": "DYNAMIC",
        "dynamic_time_period": {
            "latest_n_deliverables": data_lineage.get("dynamic_latest_n", 5),
            "include_live_wave": True,
        },
    }

    try:
        report = client.reports.generate(payload)

        # Handle cached/async reports — poll until PROCESSED
        if (report and report.get("is_cached_report")
                and report.get("cache_status") == "PROCESSING"):
            cached_id = report.get("cached_report_id")
            if cached_id:
                elapsed, poll_interval, max_wait = 0, 5, 120
                while elapsed < max_wait:
                    time.sleep(poll_interval)
                    elapsed += poll_interval
                    report = client.reports.cached_get(cached_id)
                    if report.get("cache_status") == "PROCESSED":
                        break

        records = report.get("records", []) if report else []
    except SynapseError as e:
        print(f"  Synapse API error: {e.code} — {e.message}")
        records = []
    except Exception as e:
        print(f"  Synapse API exception: {e}")
        records = []

    df = pd.DataFrame(records) if records else pd.DataFrame()
    return records, df


# ══════════════════════════════════════════════════════════════════════════════
# Phase 2: Refresh — apply mapping to update the deck
# ══════════════════════════════════════════════════════════════════════════════

def _format_cell(raw, fmt: str) -> str:
    """Format a raw value according to the mapping format string."""
    if fmt == "string":
        return str(raw)
    elif "(n" in fmt or "(s" in fmt:
        try:
            prefix = "(s = " if "(s" in fmt else "(n = "
            return f"{prefix}{int(float(raw))})" if raw and float(raw) != 0 else ""
        except (ValueError, TypeError):
            return str(raw) if raw else ""
    elif "%" in fmt:
        try:
            v = float(raw)
            return f"{v:.0%}" if abs(v) <= 1.0 else f"{int(v)}%"
        except (ValueError, TypeError):
            return str(raw) if raw else ""
    elif "{}" in fmt:
        try:
            return fmt.format(raw)
        except Exception:
            return str(raw) if raw else ""
    else:
        return str(raw) if raw else ""


def _write_cell_text(cell, text: str) -> None:
    """Write text into a table cell preserving formatting."""
    for p in cell.text_frame.paragraphs:
        for r in p.runs:
            r.text = ""
    if cell.text_frame.paragraphs and cell.text_frame.paragraphs[0].runs:
        cell.text_frame.paragraphs[0].runs[0].text = text


def refresh_slide_from_mapping(
    pptx_path: str,
    output_path: str,
    slide_index: int,
    mapping: dict,
    data_lineage: dict,
) -> dict:
    """Apply a mapping dict to refresh charts + tables on one slide.

    Returns results dict with status per chart/table.

    mapping format:
    {
      "charts": [
        {"chart_name": "Chart 35", "segment_filter": "CARD",
         "series_column": "x_code", "series_name_map": {"IDK": "0"},
         "row_field": "y_label", "value_field": "percentage"}
      ],
      "tables": [
        {"table_name": "Table 25", "segment_filter": "CARD",
         "columns": [
           {"header": "Product", "data_field": "y_label", "format": "string"},
           {"header": "Base", "data_field": "base", "format": "(n = {})"},
           {"header": "", "data_field": null, "format": "spacer"},
           {"header": "Easy", "data_field": "percentage", "format": "{}%",
            "filter": {"x_code": "H"}}
         ]}
      ]
    }
    """
    # Fetch data
    records, df = fetch_synapse_data(data_lineage)
    if df.empty:
        return {"error": "No data returned from Synapse API"}

    # Read source for series order
    src_prs = Presentation(pptx_path)
    src_slide = src_prs.slides[slide_index]
    src_chart_series = {}
    for shape in src_slide.shapes:
        if shape.has_chart:
            src_chart_series[shape.name] = [
                str(s.name) for s in shape.chart.plots[0].series
            ]

    # Clone + refresh
    shutil.copy2(pptx_path, output_path)
    prs = Presentation(output_path)
    slide = prs.slides[slide_index]
    chart_shapes = {s.name: s for s in slide.shapes if s.has_chart}
    table_shapes = {s.name: s for s in slide.shapes if s.has_table}
    ns_c = "http://schemas.openxmlformats.org/drawingml/2006/chart"

    results = {"charts": [], "tables": []}

    # ── Charts ──
    for cm in mapping.get("charts", []):
        name = cm["chart_name"]
        shape = chart_shapes.get(name)
        if not shape:
            results["charts"].append({"name": name, "status": "not_found"})
            continue

        sub = df.copy()
        seg = cm.get("segment_filter")
        if seg and "segment_1" in sub.columns:
            sub = sub[sub["segment_1"] == seg]
        tp = cm.get("time_period")
        if tp and "time_period_name" in sub.columns:
            sub = sub[sub["time_period_name"] == tp]
        if sub.empty:
            results["charts"].append({"name": name, "status": "empty"})
            continue

        row_f = cm.get("row_field", "y_label")
        col_f = cm.get("series_column")
        val_f = cm.get("value_field", "percentage")
        name_map = cm.get("series_name_map", {})

        try:
            if col_f and col_f in sub.columns:
                pivot = sub.pivot_table(
                    index=row_f, columns=col_f, values=val_f, aggfunc="first",
                )
            else:
                pivot = sub.groupby(row_f, sort=False)[val_f].first().to_frame()

            categories = list(pivot.index.astype(str))

            # Apply explicit category order from mapping if provided.
            # Otherwise try to match source chart's category order.
            cat_order = cm.get("category_order")
            if cat_order:
                order = [categories.index(c) for c in cat_order if c in categories]
                extra = [i for i in range(len(categories)) if i not in order]
                reorder = order + extra
                categories = [categories[i] for i in reorder]
                pivot = pivot.iloc[reorder]

            orig_series = src_chart_series.get(name, [])

            series_data = []
            for sn in orig_series:
                data_val = name_map.get(sn, sn)
                matched = None
                for pc in pivot.columns:
                    if str(pc) == data_val or str(pc).lower() == data_val.lower():
                        matched = pc
                        break
                # For single-column pivots (no series_column), use the only column
                if matched is None and len(pivot.columns) == 1:
                    matched = pivot.columns[0]
                vals = (
                    [0.0 if pd.isna(v) else round(float(v), 4) for v in pivot[matched]]
                    if matched is not None
                    else [0.0] * len(categories)
                )
                series_data.append((sn, vals))

            src_fmts = [
                fc.text
                for fc in shape.chart._chartSpace.iter(f"{{{ns_c}}}formatCode")
            ]
            cd = CategoryChartData()
            cd.categories = categories
            for sn, vals in series_data:
                cd.add_series(sn, vals)
            shape.chart.replace_data(cd)
            for i, fc_el in enumerate(
                shape.chart._chartSpace.iter(f"{{{ns_c}}}formatCode")
            ):
                if i < len(src_fmts):
                    fc_el.text = src_fmts[i]

            results["charts"].append({
                "name": name, "status": "ok", "segment": seg,
                "categories": categories[:3], "n_series": len(series_data),
            })
        except Exception as e:
            results["charts"].append({
                "name": name, "status": "error", "error": str(e),
            })

    # ── Tables ──
    for tm in mapping.get("tables", []):
        name = tm["table_name"]

        # Skip static reference tables (e.g. message description lookup tables)
        if tm.get("static"):
            results["tables"].append({"name": name, "status": "static_skipped"})
            continue

        shape = table_shapes.get(name)
        if not shape:
            results["tables"].append({"name": name, "status": "not_found"})
            continue

        tbl = shape.table
        sub = df.copy()

        # Apply global segment filter
        seg = tm.get("segment_filter")
        if seg and "segment_1" in sub.columns:
            sub = sub[sub["segment_1"] == seg]

        # Apply time period filter
        tp = tm.get("time_period")
        if tp and "time_period_name" in sub.columns:
            sub = sub[sub["time_period_name"] == tp]

        columns_spec = tm.get("columns", [])
        if not columns_spec:
            results["tables"].append({"name": name, "status": "no_columns"})
            continue

        # Determine if this is a row-iterated table or a single-row summary table.
        # Single-row: every column has its own filter (e.g. sample size per segment).
        # Row-iterated: columns share a row key field.
        all_have_filters = all(cs.get("filter") for cs in columns_spec if cs.get("data_field"))
        row_key = None
        if not all_have_filters:
            for cs in columns_spec:
                if cs.get("data_field") and cs.get("format") != "spacer":
                    row_key = cs["data_field"]
                    break

        try:
            if all_have_filters and not row_key:
                # ── Single-row summary table (e.g. base sizes per segment) ──
                # Each column independently queries the data with its own filter.
                # Write into header row (row 0) or first data row (row 1).
                target_row = 1 if len(tbl.rows) > 1 else 0
                for ci, cs in enumerate(columns_spec):
                    if ci >= len(tbl.columns):
                        break
                    fmt = cs.get("format", "string")
                    data_f = cs.get("data_field")
                    col_filter = cs.get("filter")
                    if not data_f:
                        continue

                    cell_sub = df.copy()  # start from unfiltered
                    if tp and "time_period_name" in cell_sub.columns:
                        cell_sub = cell_sub[cell_sub["time_period_name"] == tp]
                    if col_filter and isinstance(col_filter, dict):
                        for fk, fv in col_filter.items():
                            if fk in cell_sub.columns:
                                cell_sub = cell_sub[cell_sub[fk] == fv]
                    if cell_sub.empty or data_f not in cell_sub.columns:
                        continue

                    # Take first row's value (or max for base)
                    raw = cell_sub.iloc[0][data_f]
                    text = _format_cell(raw, fmt)

                    cell = tbl.cell(target_row, ci)
                    _write_cell_text(cell, text)

                results["tables"].append({
                    "name": name, "status": "ok", "segment": seg, "rows": 1,
                })
            else:
                # ── Row-iterated table ──
                if not row_key or (sub.empty and not all_have_filters):
                    results["tables"].append({"name": name, "status": "no_row_key"})
                    continue
                if sub.empty:
                    results["tables"].append({"name": name, "status": "empty"})
                    continue
                if row_key not in sub.columns:
                    results["tables"].append({"name": name, "status": "missing_col",
                                              "col": row_key})
                    continue

                keys = sub[row_key].dropna().unique().tolist()
                n_rows = min(len(keys), len(tbl.rows) - 1)

                for ri in range(n_rows):
                    row_data = sub[sub[row_key] == keys[ri]]
                    if row_data.empty:
                        continue
                    for ci, cs in enumerate(columns_spec):
                        if ci >= len(tbl.columns) or ri + 1 >= len(tbl.rows):
                            break
                        fmt = cs.get("format", "string")
                        data_f = cs.get("data_field")
                        col_filter = cs.get("filter")
                        if fmt == "spacer" or not data_f:
                            continue

                        cell_data = row_data
                        if col_filter and isinstance(col_filter, dict):
                            for fk, fv in col_filter.items():
                                if fk in cell_data.columns:
                                    cell_data = cell_data[cell_data[fk] == fv]
                        if cell_data.empty or data_f not in cell_data.columns:
                            continue

                        raw = cell_data.iloc[0][data_f]
                        text = _format_cell(raw, fmt)

                        cell = tbl.cell(ri + 1, ci)
                        _write_cell_text(cell, text)

                results["tables"].append({
                    "name": name, "status": "ok", "segment": seg, "rows": n_rows,
                })
        except Exception as e:
            results["tables"].append({
                "name": name, "status": "error", "error": str(e),
            })

    prs.save(output_path)
    return results


# ══════════════════════════════════════════════════════════════════════════════
# Headline Writer
# ══════════════════════════════════════════════════════════════════════════════

def write_headline(pptx_path: str, slide_index: int, headline_text: str) -> None:
    """Write a headline into the slide's headline text shape (top area, largest text).

    Finds the headline shape: text shape in the top 1.5" zone with the longest text.
    Clears all runs, writes the new headline text into the first run preserving formatting.
    Saves the PPTX.
    """
    prs = Presentation(pptx_path)
    slide = prs.slides[slide_index]

    # Find headline shape: text shapes in top 1.5" zone, pick the one with longest text
    TOP_ZONE = 1.5  # inches
    candidates = []
    for shape in slide.shapes:
        if not shape.has_text_frame:
            continue
        top_in = _in(shape.top)
        if top_in > TOP_ZONE:
            continue
        text = shape.text_frame.text.strip()
        if text:
            candidates.append((shape, len(text)))

    if not candidates:
        raise ValueError(
            f"No text shapes found in top {TOP_ZONE}\" zone of slide {slide_index}"
        )

    # Pick shape with longest existing text (most likely the headline)
    headline_shape = max(candidates, key=lambda x: x[1])[0]

    # Preserve first paragraph's first run formatting, clear everything else
    first_para = headline_shape.text_frame.paragraphs[0]

    # Save formatting from first run if it exists
    saved_font = None
    if first_para.runs:
        run = first_para.runs[0]
        saved_font = {
            "bold": run.font.bold,
            "italic": run.font.italic,
            "size": run.font.size,
            "color_rgb": run.font.color.rgb if run.font.color and run.font.color.rgb else None,
            "name": run.font.name,
        }

    # Clear all runs in all paragraphs
    for para in headline_shape.text_frame.paragraphs:
        for run in para.runs:
            run.text = ""

    # Write new headline text into first run of first paragraph
    if first_para.runs:
        first_para.runs[0].text = headline_text
    else:
        # No runs exist — add one
        run = first_para.add_run()
        run.text = headline_text
        if saved_font:
            if saved_font["bold"] is not None:
                run.font.bold = saved_font["bold"]
            if saved_font["italic"] is not None:
                run.font.italic = saved_font["italic"]
            if saved_font["size"] is not None:
                run.font.size = saved_font["size"]
            if saved_font["color_rgb"] is not None:
                run.font.color.rgb = saved_font["color_rgb"]
            if saved_font["name"] is not None:
                run.font.name = saved_font["name"]

    prs.save(pptx_path)


# ══════════════════════════════════════════════════════════════════════════════
# Deck-level refresh from a single spec JSON
# ══════════════════════════════════════════════════════════════════════════════

def refresh_deck_from_spec(spec_path: str, pptx_path: str = None, output_path: str = None) -> dict:
    """Refresh a deck using a single spec JSON file.

    Spec JSON format:
    {
      "source_deck": "deck.pptx",
      "data_sources": {
        "source_key": {"project_id": ..., "reporting_plan_id": ..., ...}
      },
      "slides": [
        {"slide_index": 4, "data_source": "source_key", "components": [...]}
      ]
    }

    Fetches data per data_source (cached), then refreshes each slide's components.
    Returns results dict.
    """
    spec = json.loads(Path(spec_path).read_text(encoding="utf-8"))
    spec_dir = Path(spec_path).parent

    # Resolve paths
    if pptx_path is None:
        pptx_path = str(spec_dir / spec["source_deck"])
    if output_path is None:
        stem = Path(spec["source_deck"]).stem
        ext = Path(spec["source_deck"]).suffix
        output_path = str(spec_dir / f"Output_{stem}{ext}")

    # Reconcile spec against embedded config if present
    embedded = read_embedded_config(pptx_path)
    if embedded:
        result = reconcile_spec_with_config(spec, embedded)
        spec = result["spec"]
        changes = result["changes"]
        if changes["reordered"]:
            print(f"  Reconciled: {len(changes['reordered'])} slides reordered")
        if changes["added"]:
            print(f"  Reconciled: {len(changes['added'])} slides added (need interpretation)")
        if changes["deleted"]:
            print(f"  Reconciled: {len(changes['deleted'])} slides deleted (removed from spec)")

    data_sources = spec.get("data_sources", {})
    slides = spec.get("slides", [])

    # Read source series order for all slides
    src_prs = Presentation(pptx_path)
    src_series_by_slide = {}
    for slide_spec in slides:
        si = slide_spec["slide_index"]
        if si < len(src_prs.slides):
            src_series_by_slide[si] = {}
            for shape in src_prs.slides[si].shapes:
                if shape.has_chart:
                    src_series_by_slide[si][shape.name] = [
                        str(s.name) for s in shape.chart.plots[0].series
                    ]

    # Clone source -> output
    shutil.copy2(pptx_path, output_path)
    prs = Presentation(output_path)

    # Cache fetched data by data_source key
    data_cache = {}
    all_results = {"slides": [], "output": output_path}
    ns_c = "http://schemas.openxmlformats.org/drawingml/2006/chart"

    for slide_spec in slides:
        si = slide_spec["slide_index"]
        ds_key = slide_spec.get("data_source")
        if si >= len(prs.slides):
            all_results["slides"].append({"slide_index": si, "error": "out of range"})
            continue

        slide = prs.slides[si]

        # Fetch data (cached by data_source key)
        if ds_key and ds_key not in data_cache:
            lineage = data_sources.get(ds_key, {})
            if lineage:
                print(f"  Fetching data_source '{ds_key}': project={lineage.get('project_id')}, "
                      f"analysis={lineage.get('analysis_ids')}")
                records, df = fetch_synapse_data(lineage)
                data_cache[ds_key] = df
                print(f"    -> {len(records)} records")
            else:
                data_cache[ds_key] = pd.DataFrame()

        df = data_cache.get(ds_key, pd.DataFrame())
        if df.empty:
            all_results["slides"].append({"slide_index": si, "error": "no data"})
            continue

        # Index shapes by name
        chart_shapes = {s.name: s for s in slide.shapes if s.has_chart}
        table_shapes = {s.name: s for s in slide.shapes if s.has_table}
        src_chart_series = src_series_by_slide.get(si, {})

        slide_results = {"slide_index": si, "charts": [], "tables": []}

        # Convert DataFrame to records once per slide (used by raw config path)
        records_list = df.to_dict("records")

        # Read static_time_period_names — check slide-level first, then data source
        lineage = data_sources.get(ds_key, {})
        lin_raw_static_names = (
            slide_spec.get("static_time_period_names")
            or lineage.get("static_time_period_names")
        )

        for comp in slide_spec.get("components", []):
            name = comp.get("name", "")
            ctype = comp.get("type", "")

            if comp.get("static"):
                slide_results["tables"].append({"name": name, "status": "static_skipped"})
                continue

            raw_pc = comp.get("raw_pivot_config")
            raw_mc = comp.get("raw_mapping_config")

            # ── RAW CONNECTOR PATH ──
            # When a component has raw_pivot_config + raw_mapping_config at the
            # top level, use pivot_records_to_chart_data() for exact Connector
            # fidelity.  This handles connected slides.
            if raw_pc and raw_mc:
                from slidegen.synapse_chart_mapper import pivot_records_to_chart_data

                static_names = lin_raw_static_names
                chart_pattern = comp.get("chart_pattern", "")
                split_order = comp.get("split_order")
                rows_per_object = comp.get("rows_per_object")
                top_n_rows = comp.get("top_n_rows")

                if ctype == "chart":
                    shape = chart_shapes.get(name)
                    if not shape:
                        slide_results["charts"].append({"name": name, "status": "not_found"})
                        continue

                    try:
                        chart_data = pivot_records_to_chart_data(
                            records_list, raw_pc, raw_mc,
                            static_time_period_names=static_names,
                            chart_pattern=chart_pattern,
                            split_order=split_order,
                            rows_per_object=rows_per_object,
                            top_n_rows=top_n_rows,
                        )

                        if not chart_data.success or not chart_data.categories:
                            slide_results["charts"].append({
                                "name": name, "status": "empty",
                                "error": chart_data.error,
                            })
                            continue

                        cats = chart_data.categories
                        series_data = chart_data.series

                        # Reorder categories to match source chart's order
                        # (pivot may return alphabetical; source has Connector's order)
                        try:
                            src_chart = None
                            for ss in src_prs.slides[si].shapes:
                                if ss.has_chart and ss.name == name:
                                    src_chart = ss
                                    break
                            if src_chart:
                                src_cats = [str(c) for c in src_chart.chart.plots[0].categories]
                                if set(src_cats) == set(cats) and src_cats != cats:
                                    order = [cats.index(sc) for sc in src_cats if sc in cats]
                                    if len(order) == len(cats):
                                        cats = [cats[i] for i in order]
                                        series_data = [(n, [v[i] for i in order])
                                                       for n, v in series_data]
                        except Exception:
                            pass

                        # Save formatCodes from source chart BEFORE replace_data
                        src_fmts = [
                            fc.text for fc in shape.chart._chartSpace.iter(
                                f"{{{ns_c}}}formatCode")
                        ]

                        # Build chart data object
                        chart_type_str = chart_pattern
                        if "scatter" in chart_type_str or "xy_" in chart_type_str:
                            # XY scatter / abacus: sort by first series value desc
                            cd = XyChartData()
                            n_cats = len(cats)
                            if series_data and series_data[0][1]:
                                order = sorted(
                                    range(n_cats),
                                    key=lambda i: (series_data[0][1][i]
                                                   if i < len(series_data[0][1]) else 0),
                                    reverse=True,
                                )
                            else:
                                order = list(range(n_cats))
                            for sname, vals in series_data:
                                s = cd.add_series(sname)
                                for rank, oi in enumerate(order):
                                    x_val = round(vals[oi], 2) if oi < len(vals) else 0.0
                                    y_val = float(n_cats - rank)
                                    s.add_data_point(x_val, y_val)
                        else:
                            # Standard CategoryChartData
                            cd = CategoryChartData()
                            cd.categories = cats
                            for sname, vals in series_data:
                                cd.add_series(sname, [round(v, 2) for v in vals])

                        shape.chart.replace_data(cd)

                        # Restore formatCodes from source (replace_data resets them)
                        for i, fc_el in enumerate(
                            shape.chart._chartSpace.iter(f"{{{ns_c}}}formatCode")
                        ):
                            if i < len(src_fmts):
                                fc_el.text = src_fmts[i]

                        slide_results["charts"].append({
                            "name": name, "status": "ok",
                            "categories": len(cats), "series": len(series_data),
                            "mode": "raw_connector",
                        })
                    except Exception as e:
                        slide_results["charts"].append({
                            "name": name, "status": "error", "error": str(e),
                            "mode": "raw_connector",
                        })

                elif ctype in ("value_table", "label_table"):
                    shape = table_shapes.get(name)
                    if not shape:
                        slide_results["tables"].append({"name": name, "status": "not_found"})
                        continue

                    tbl = shape.table

                    # For connected tables, restore from source (reliable).
                    # Table refresh from pivot configs is complex and fragile
                    # across table types. Charts are the high-value refresh target.
                    try:
                        src_tbl_shape = None
                        for s2 in src_prs.slides[si].shapes:
                            if s2.has_table and s2.name == name:
                                src_tbl_shape = s2
                                break
                        if src_tbl_shape:
                            src_tbl = src_tbl_shape.table
                            for r in range(min(len(src_tbl.rows), len(tbl.rows))):
                                for c in range(min(len(src_tbl.columns), len(tbl.columns))):
                                    _write_cell_text(
                                        tbl.cell(r, c),
                                        src_tbl.cell(r, c).text.strip(),
                                    )
                            slide_results["tables"].append({
                                "name": name, "status": "ok", "mode": "source_restore",
                            })
                        else:
                            slide_results["tables"].append({
                                "name": name, "status": "no_source",
                            })
                    except Exception as e2:
                        slide_results["tables"].append({
                            "name": name, "status": "error", "error": str(e2),
                        })

                continue  # skip to next component

            # ── INTERPRETED MAPPING PATH ──
            # When a component has data_mapping with row_field/series_column/value_field,
            # use the existing pandas-based pivot logic (non-connected slides).
            dm = comp.get("data_mapping", {})
            if not dm:
                continue

            # Apply filters
            sub = df.copy()
            seg = dm.get("segment_filter")
            if seg and "segment_1" in sub.columns:
                sub = sub[sub["segment_1"] == seg]
            tp = dm.get("time_period")
            if tp and "time_period_name" in sub.columns:
                sub = sub[sub["time_period_name"] == tp]

            if ctype == "chart":
                shape = chart_shapes.get(name)
                if not shape:
                    slide_results["charts"].append({"name": name, "status": "not_found"})
                    continue
                if sub.empty:
                    slide_results["charts"].append({"name": name, "status": "empty"})
                    continue

                row_f = dm.get("row_field", "y_label")
                col_f = dm.get("series_column")
                val_f = dm.get("value_field", "percentage")
                name_map = dm.get("series_name_map", {})

                try:
                    if col_f and col_f in sub.columns:
                        pivot = sub.pivot_table(index=row_f, columns=col_f,
                                                values=val_f, aggfunc="first")
                    else:
                        pivot = sub.groupby(row_f, sort=False)[val_f].first().to_frame()

                    categories = list(pivot.index.astype(str))

                    # Apply category order
                    cat_order = dm.get("category_order")
                    if cat_order:
                        order = [categories.index(c) for c in cat_order if c in categories]
                        extra = [i for i in range(len(categories)) if i not in order]
                        reorder = order + extra
                        categories = [categories[i] for i in reorder]
                        pivot = pivot.iloc[reorder]

                    orig_series = src_chart_series.get(name, [])
                    series_data = []
                    for sn in orig_series:
                        data_val = name_map.get(sn, sn)
                        matched = None
                        for pc in pivot.columns:
                            if str(pc) == data_val or str(pc).lower() == data_val.lower():
                                matched = pc
                                break
                        if matched is None and len(pivot.columns) == 1:
                            matched = pivot.columns[0]
                        vals = ([0.0 if pd.isna(v) else round(float(v), 4) for v in pivot[matched]]
                                if matched is not None else [0.0] * len(categories))
                        series_data.append((sn, vals))

                    # Save + restore formatCodes
                    src_fmts = [fc.text for fc in shape.chart._chartSpace.iter(f"{{{ns_c}}}formatCode")]
                    cd = CategoryChartData()
                    cd.categories = categories
                    for sn, vals in series_data:
                        cd.add_series(sn, vals)
                    shape.chart.replace_data(cd)
                    for i, fc_el in enumerate(shape.chart._chartSpace.iter(f"{{{ns_c}}}formatCode")):
                        if i < len(src_fmts):
                            fc_el.text = src_fmts[i]

                    slide_results["charts"].append({
                        "name": name, "status": "ok", "segment": seg,
                        "categories": len(categories), "series": len(series_data),
                    })
                except Exception as e:
                    slide_results["charts"].append({"name": name, "status": "error", "error": str(e)})

            elif ctype == "table":
                shape = table_shapes.get(name)
                if not shape:
                    slide_results["tables"].append({"name": name, "status": "not_found"})
                    continue

                tbl = shape.table
                columns_spec = dm.get("columns", [])
                if not columns_spec:
                    continue

                try:
                    all_have_filters = all(cs.get("filter") for cs in columns_spec if cs.get("data_field"))
                    row_key = None
                    if not all_have_filters:
                        for cs in columns_spec:
                            if cs.get("data_field") and cs.get("format") != "spacer":
                                row_key = cs["data_field"]
                                break

                    if all_have_filters and not row_key:
                        # Single-row summary table
                        target_row = 1 if len(tbl.rows) > 1 else 0
                        for ci, cs in enumerate(columns_spec):
                            if ci >= len(tbl.columns):
                                break
                            data_f = cs.get("data_field")
                            col_filter = cs.get("filter")
                            if not data_f:
                                continue
                            cell_sub = df.copy()
                            if tp and "time_period_name" in cell_sub.columns:
                                cell_sub = cell_sub[cell_sub["time_period_name"] == tp]
                            if col_filter:
                                for fk, fv in col_filter.items():
                                    if fk in cell_sub.columns:
                                        cell_sub = cell_sub[cell_sub[fk] == fv]
                            if cell_sub.empty or data_f not in cell_sub.columns:
                                continue
                            _write_cell_text(tbl.cell(target_row, ci),
                                             _format_cell(cell_sub.iloc[0][data_f], cs.get("format", "string")))

                        slide_results["tables"].append({"name": name, "status": "ok", "rows": 1})
                    else:
                        if not row_key or sub.empty or row_key not in sub.columns:
                            slide_results["tables"].append({"name": name, "status": "no_data"})
                            continue

                        # Apply table-level category order
                        cat_order = dm.get("category_order")
                        keys = sub[row_key].dropna().unique().tolist()
                        if cat_order:
                            ordered = [k for k in cat_order if k in keys]
                            extra = [k for k in keys if k not in ordered]
                            keys = ordered + extra

                        n_rows = min(len(keys), len(tbl.rows) - 1)
                        for ri in range(n_rows):
                            row_data = sub[sub[row_key] == keys[ri]]
                            if row_data.empty:
                                continue
                            for ci, cs in enumerate(columns_spec):
                                if ci >= len(tbl.columns) or ri + 1 >= len(tbl.rows):
                                    break
                                fmt = cs.get("format", "string")
                                data_f = cs.get("data_field")
                                col_filter = cs.get("filter")
                                if fmt == "spacer" or not data_f:
                                    continue
                                cell_data = row_data
                                if col_filter:
                                    for fk, fv in col_filter.items():
                                        if fk in cell_data.columns:
                                            cell_data = cell_data[cell_data[fk] == fv]
                                if cell_data.empty or data_f not in cell_data.columns:
                                    continue
                                _write_cell_text(tbl.cell(ri + 1, ci),
                                                 _format_cell(cell_data.iloc[0][data_f], fmt))

                        slide_results["tables"].append({"name": name, "status": "ok", "rows": n_rows})
                except Exception as e:
                    slide_results["tables"].append({"name": name, "status": "error", "error": str(e)})

        all_results["slides"].append(slide_results)

    prs.save(output_path)
    return all_results


# ══════════════════════════════════════════════════════════════════════════════
# CLI
# ══════════════════════════════════════════════════════════════════════════════

def main():
    import argparse

    parser = argparse.ArgumentParser(
        description="Intelligent slide refresh pipeline",
    )
    sub = parser.add_subparsers(dest="command")

    # ── embed-config: scan PPTX and write config into it ──
    p_embed = sub.add_parser("embed-config", help="Generate and embed config into PPTX")
    p_embed.add_argument("--pptx", required=True, help="PPTX to embed config into")

    # ── show-config: read and display embedded config ──
    p_show = sub.add_parser("show-config", help="Show the embedded config from a PPTX")
    p_show.add_argument("--pptx", required=True, help="PPTX to read config from")

    # ── read: extract slide context for interpretation ──
    p_read = sub.add_parser("read", help="Extract slide context for Claude Code interpretation")
    p_read.add_argument("--pptx", required=True, help="Source PPTX path")
    p_read.add_argument("--slide", type=int, default=0, help="Slide index (0-based)")
    p_read.add_argument("--lineage", type=str, default=None,
                        help="Data lineage JSON (also fetches Synapse data)")

    # ── refresh: refresh one slide ──
    p_refresh = sub.add_parser("refresh", help="Refresh one slide from mapping + lineage")
    p_refresh.add_argument("--pptx", required=True)
    p_refresh.add_argument("--output", required=True)
    p_refresh.add_argument("--slide", type=int, default=0)
    p_refresh.add_argument("--mapping", required=True)
    p_refresh.add_argument("--lineage", required=True)

    # ── refresh-deck: refresh all slides from spec JSON ──
    p_deck = sub.add_parser("refresh-deck", help="Refresh all slides from spec JSON")
    p_deck.add_argument("--spec", required=True, help="Spec JSON (same name as PPTX)")
    p_deck.add_argument("--pptx", default=None, help="Source PPTX (default: from spec)")
    p_deck.add_argument("--output", default=None, help="Output (default: Output_<source>)")

    # ── headline: write headline into slide ──
    p_headline = sub.add_parser("headline", help="Write headline text into a slide")
    p_headline.add_argument("--pptx", required=True)
    p_headline.add_argument("--slide", type=int, default=0)
    p_headline.add_argument("--text", required=True)

    args = parser.parse_args()

    if args.command == "embed-config":
        config = generate_embedded_config(args.pptx)
        write_embedded_config(args.pptx, config)
        print(json.dumps(config, indent=2, ensure_ascii=False))
        print(f"\nConfig embedded into {args.pptx}")

    elif args.command == "show-config":
        config = read_embedded_config(args.pptx)
        if config:
            print(json.dumps(config, indent=2, ensure_ascii=False))
        else:
            print("No SlideGen config found in this PPTX.")

    elif args.command == "read":
        context = read_slide_context(args.pptx, slide_index=args.slide)
        print(format_slide_for_interpretation(context))
        if args.lineage:
            lineage = json.loads(Path(args.lineage).read_text(encoding="utf-8"))
            records, df = fetch_synapse_data(lineage)
            print()
            print(format_data_for_interpretation(df))

    elif args.command == "refresh":
        mapping = json.loads(Path(args.mapping).read_text(encoding="utf-8"))
        lineage = json.loads(Path(args.lineage).read_text(encoding="utf-8"))
        results = refresh_slide_from_mapping(
            args.pptx, args.output, args.slide, mapping, lineage,
        )
        print(json.dumps(results, indent=2, ensure_ascii=False))

    elif args.command == "refresh-deck":
        results = refresh_deck_from_spec(args.spec, args.pptx, args.output)
        print(json.dumps(results, indent=2, ensure_ascii=False))

    elif args.command == "headline":
        write_headline(args.pptx, args.slide, args.text)
        print(f"Headline written to slide {args.slide}: \"{args.text}\"")

    else:
        parser.print_help()


if __name__ == "__main__":
    main()
